--FIX Terminal Output

SET LINESIZE 32767;
SET TRIMSPOOL ON;
SET TRIMOUT ON;
SET WRAP OFF;
COLUMN lastLogin FORMAT a15;
COLUMN profile_ID FORMAT a5;
COLUMN friend_ID FORMAT a5;
COLUMN group_ID FORMAT a5;
COLUMN groupName FORMAT a5;
COLUMN subject FORMAT a15;
COLUMN messageText FORMAT a40;



