INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (1,'G1','adipiscing, enim mi tempor lorem,',3,77);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (2,'G2','testing',6,95);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (3,'G3','eu, euismod ac, fermentum vel,',23,51);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (4,'G4','lobortis. Class aptent taciti sociosqu',5,33);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (5,'G5','at pretium aliquet, metus urna',4,99);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (6,'G6','neque sed dictum eleifend, nunc',16,68);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (7,'G7','Cum sociis natoque penatibus et',3,79);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (8,'G8','dolor vitae dolor. Donec fringilla.',15,12);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (9,'G9','eu dui. Cum sociis natoque',26,81);
INSERT INTO Groups (group_ID,groupName,description,memberLimit,numMembers) VALUES (10,'G10','feugiat nec, diam. Duis mi',27,23);
